#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/leandro/.Xmodmap"
setxkbmap us -variant intl

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# xrandr --output LVDS1 --off --output VGA1 --auto &
nitrogen --restore &
nm-applet &
xcompmgr &
volumeicon &
paramano &
xfce4-clipman &
plank &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/leandro/.fluxbox/log"
